permissions:
  contents: write

name: Auto Update README with Swagger Docs

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: ci

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build & Run Spring Boot App
        run: |
          ./mvnw clean spring-boot:run &
          sleep 25

      - name: Install Swagger Markdown Tool
        run: npm install -g swagger-markdown

      - name: Update README with API Docs
        run: bash scripts/update-readme.sh

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: auto-update API docs in README" || echo "No changes"
          git pull --rebase
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main